language: python
python:
  - '2.7'
  - '3.4'
services:
  - elasticsearch
install:
  - travis_retry pip install -e .
  - travis_retry pip install file://$(pwd)#egg=djes_file_fields[dev]
script:
  - py.test --cov djes_file_fields --cov-report term-missing
after_success:
  - coveralls
sudo: false
